[server]
fileWatcherType = "none"
runOnSave = false
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[global]
developmentMode = false

[browser]
gatherUsageStats = false

[theme]
base = "light"