[server]
fileWatcherType = "none"
runOnSave = false
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[global]
developmentMode = false
disableWatchdogWarning = true
showWarningOnDirectExecution = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "error" 